import React from 'react';

export default class Text extends React.Component{
	render() {
		return (<div style = {{ padding: '0px 10px 0px', overflow: 'scroll' }}>
            <p>{"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id eros molestie, imperdiet metus vel, vulputate orci. Aenean dictum, elit eu vulputate faucibus, erat sem imperdiet felis, eget semper nulla arcu id lacus. Nulla sit amet mollis enim. Morbi pharetra, ex sed efficitur molestie, risus dolor pretium justo, id consectetur sem lectus vel dui. Sed mollis nisl vitae lobortis semper. Suspendisse hendrerit sem quis feugiat malesuada. Duis ut scelerisque lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus."}</p>
            <p>{"In fringilla nunc faucibus, viverra tortor ut, aliquam tellus. Nam sagittis erat non luctus luctus. Curabitur pulvinar nibh ac lacinia fringilla. Sed posuere vestibulum elit. Praesent lacinia eget arcu quis molestie. Donec nec ultrices elit, eget scelerisque orci. Aenean faucibus convallis eros, non pulvinar nibh interdum non. Nunc quis neque ultricies, dapibus dolor a, sagittis mi. Phasellus tempus est sem. Nam iaculis id quam at faucibus. In ipsum ante, ultrices ut suscipit quis, pharetra sit amet erat. Ut at aliquet orci. Vivamus enim leo, consequat ut augue sit amet, sagittis porta justo."}</p>
            <p>{"Vestibulum dui nunc, pretium at congue a, tempus id purus. Quisque venenatis vestibulum mattis. Nulla facilisi. Sed nisl urna, interdum ut scelerisque et, cursus non elit. Suspendisse potenti. Sed nunc velit, bibendum fermentum faucibus vitae, iaculis vel felis. Sed semper augue sollicitudin odio accumsan fringilla. Donec finibus purus auctor pharetra rhoncus. Sed placerat tellus sit amet luctus pharetra. Morbi rhoncus mollis vehicula. Cras nec orci urna. Suspendisse viverra ultrices convallis. Vestibulum lacus tortor, pharetra nec purus eleifend, maximus hendrerit orci."}</p>
            <p>{"Morbi non ultrices dolor. Phasellus imperdiet diam sit amet velit vehicula consectetur. Donec rutrum, felis in viverra convallis, ex nibh lacinia ex, ut ultrices neque tortor quis nibh. Vivamus sodales sapien non eros tincidunt, ut commodo erat vulputate. Praesent vel aliquet velit. Nullam eu erat volutpat, ullamcorper mi sodales, eleifend felis. Cras aliquet placerat tincidunt. Nunc metus mauris, ultrices at orci vel, pharetra vestibulum turpis. Donec finibus, diam vel tincidunt vestibulum, orci odio condimentum urna, ac porta libero felis vel leo. Integer ut est at justo dignissim interdum."}</p>
            <p>{"Pellentesque ac ultrices sapien. Vestibulum sem velit, rutrum id lorem non, malesuada aliquet odio. Sed a dui varius risus rutrum ultricies. Aenean lacinia ornare pharetra. Maecenas vel lorem sit amet diam convallis tempor. Nunc ac justo ac felis sagittis tristique. Mauris et enim elementum, condimentum arcu lacinia, dignissim sem. Praesent nec dolor molestie, tincidunt nulla eget, viverra urna. Suspendisse ornare enim non nisl condimentum, ut aliquet enim sodales. Ut ut arcu vulputate, malesuada nibh eu, bibendum leo. Sed risus est, porttitor nec libero nec, ultricies iaculis enim. Aliquam dignissim enim sapien. Cras pretium augue in massa hendrerit vestibulum. Cras sodales dolor justo, id auctor libero ullamcorper sed. Nullam euismod pretium dui, sed accumsan metus fermentum sed. Vestibulum tempus neque in tincidunt luctus."}</p>
        </div>);
	}
}
